version: "3.9"

services:

  mongo-a:
    image: mongo
    restart: always
    volumes:
      - ./mongodb/:/opt/
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-b:
    image: mongo
    restart: always
    volumes:
      - ./mongodb/:/opt/
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  web:
    build: ./web/ # Exclude when deployed
    restart: on-failure
    depends_on:
      - "mongo-a"
      - "mongo-b"
